name: JoeyCustomEnchantedItems
version: '1.0'
main: me.shrob.joeycustomenchanteditems.JoeyCustomEnchantedItems
api-version: '1.20'

commands:
  recipes:
    description: opens the maingui for the recipes

